
    create table CANCHAS (
        codigoCancha bigint not null,
        estaIluminado boolean,
        nombre varchar(255),
        codigoColor_codigoColor bigint,
        primary key (codigoCancha)
    )

    create table COLORES (
        codigoColor bigint not null,
        descripcion varchar(255),
        primary key (codigoColor)
    )

    create table JUGADORES (
        idJugador bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(200),
        nacimiento timestamp,
        nombre varchar(128),
        idPartido_idPartido bigint not null,
        idJugador_idJugador bigint not null,
        codigoPaleta_codigoPaletas bigint,
        idPaleta_codigoPaletas bigint,
        primary key (idJugador)
    )

    create table PALETAS (
        codigoConstructor bigint not null,
        apellido varchar(255),
        domicilio varchar(200),
        nombre varchar(128),
        codigoPaletas bigint not null,
        grosor float,
        color_codigoColor bigint,
        constructor_codigoConstructor bigint,
        primary key (codigoPaletas)
    )

    create table PARTIDOS (
        idPartido bigint generated by default as identity (start with 1),
        finPartido timestamp,
        inicioPartido timestamp,
        codigoCancha_codigoCancha bigint,
        codigoColorCancha_codigoColor bigint,
        idJugadorResponsable_idJugador bigint,
        primary key (idPartido)
    )

    alter table CANCHAS 
        add constraint FK_ic50w13u6l8ildcf4tuxa3tqe 
        foreign key (codigoColor_codigoColor) 
        references COLORES

    alter table JUGADORES 
        add constraint FK_405vc678nsh7buk9vbw0p89w8 
        foreign key (idPartido_idPartido) 
        references PARTIDOS

    alter table JUGADORES 
        add constraint FK_q0hxmlljb73wu8pvoir49r3p2 
        foreign key (idJugador_idJugador) 
        references JUGADORES

    alter table JUGADORES 
        add constraint FK_1fg72lg5knh0x71gt30h4sxaw 
        foreign key (codigoPaleta_codigoPaletas) 
        references PALETAS

    alter table JUGADORES 
        add constraint FK_7huedotmxpe0bm7cjc6jnmdyt 
        foreign key (idPaleta_codigoPaletas) 
        references PALETAS

    alter table PALETAS 
        add constraint FK_tar2ha86gkt6t8r3490h6p02 
        foreign key (color_codigoColor) 
        references COLORES

    alter table PALETAS 
        add constraint FK_g0sthfrh9pjftj5n1lme421u3 
        foreign key (constructor_codigoConstructor) 
        references PALETAS

    alter table PARTIDOS 
        add constraint FK_36fg6vstgh7a1sx0ub28c168g 
        foreign key (codigoCancha_codigoCancha) 
        references CANCHAS

    alter table PARTIDOS 
        add constraint FK_lxa08bjgvfx23ltvo7u0iyw56 
        foreign key (codigoColorCancha_codigoColor) 
        references COLORES

    alter table PARTIDOS 
        add constraint FK_ly3s838wk4hwlyerun3mni2qo 
        foreign key (idJugadorResponsable_idJugador) 
        references JUGADORES
